---
version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "057959860487"
    ECR_REPO_NAME: "multicloud-prowler-repo"
    IMAGE_TAG: "latest"
    # Variáveis de Task Definition (AJUSTE ESTES VALORES!)
    TASK_FAMILY: "multicloud-prowler-task"
    CONTAINER_NAME: "prowler-runner"

phases:
  install:
    commands:
      # Instalação: Garante que o jq esteja disponível
      - echo "=== Instalando e Validando Dependências (jq) ==="
      - if ! command -v jq &> /dev/null; then echo "Instalando jq..."; apt-get update && apt-get install -y jq; fi
      - aws --version
      - docker --version

  pre_build:
    commands:
      # === 1. LOGIN E DEFINIÇÕES ===
      - echo "=== Login no ECR e Definições ==="
      - FULL_ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - NEW_IMAGE_URI="$FULL_ECR_URI/$ECR_REPO_NAME:$IMAGE_TAG"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$FULL_ECR_URI"

  build:
    commands:
      # Build: Focado em construir e taguear
      - echo "=== Construindo imagem Docker ==="
      - docker build -t prowler-repo-local -f Dockerfile.prowler .
      - docker tag prowler-repo-local:latest "$NEW_IMAGE_URI"

  post_build:
    commands:
      # Deploy: Focado em push e atualização da Task Definition
      - echo "=== 1. Publicando imagem no ECR ==="
      - docker push "$NEW_IMAGE_URI"

      - echo "=== 2. Executando Atualização da Definição de Tarefa ECS ==="
      - export NEW_IMAGE_URI="$NEW_IMAGE_URI" # Garante que a variável seja passada
      - ./update-task-definition.sh

      - echo "=== Build e Deploy Concluídos com Sucesso ==="

artifacts:
  files: []

