---
version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "057959860487"
    ECR_REPO_NAME: "multicloud-prowler-repo"
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      # Mantendo o install simples e robusto
      - echo "=== Validando dependências no ambiente de build ==="
      - if ! command -v jq &> /dev/null; then echo "Instalando jq..."; apt-get update && apt-get install -y jq; fi
      - aws --version
      - docker --version

  pre_build:
    commands:
      # Mantendo o pre_build
      - echo "=== Login no ECR ==="
      - FULL_ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$FULL_ECR_URI"

  build:
    commands:
      # Mantendo o build
      - echo "=== Construindo imagem Docker ==="
      - docker build -t prowler-repo-local -f Dockerfile.prowler .
      - FULL_ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - docker tag prowler-repo-local:latest "$FULL_ECR_URI/$ECR_REPO_NAME:$IMAGE_TAG"

  post_build:
    commands:
      # USANDO SINTAXE DE BLOCO (|) PARA EVITAR ERROS DE INDENTAÇÃO
      - echo "=== Publicando imagem no ECR ==="
      - |
        FULL_ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
        TIMESTAMP_TAG=$(date +%Y%m%d%H%M%S)
        
        # Tag com o TIMESTAMP
        docker tag prowler-repo-local:latest "$FULL_ECR_URI/$ECR_REPO_NAME:$TIMESTAMP_TAG"
        
        # Push da TAG 'latest' e da TAG de TIMESTAMP
        docker push "$FULL_ECR_URI/$ECR_REPO_NAME:$IMAGE_TAG"
        docker push "$FULL_ECR_URI/$ECR_REPO_NAME:$TIMESTAMP_TAG"
        
        echo "=== Build concluído com sucesso. Imagens publicadas: $IMAGE_TAG e $TIMESTAMP_TAG ==="

artifacts:
  files: []