---
version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "057959860487"
    ECR_REPO_NAME: "multicloud-prowler-repo"
    IMAGE_TAG: "latest"
    # Variáveis de Task Definition (AJUSTE ESTES VALORES!)
    TASK_FAMILY: "multicloud-prowler-task"
    CONTAINER_NAME: "prowler-runner"

phases:
  install:
    commands:
      # Instalação: Garante que o jq esteja disponível
      - echo "=== Instalando e Validando Dependências (jq) ==="
      - if ! command -v jq &> /dev/null; then echo "Instalando jq..."; apt-get update && apt-get install -y jq; fi
      - aws --version
      - docker --version

  pre_build:
    commands:
      # === 1. LOGIN E DEFINIÇÕES ===
      - echo "=== Login no ECR e Definições ==="
      - FULL_ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - NEW_IMAGE_URI="$FULL_ECR_URI/$ECR_REPO_NAME:$IMAGE_TAG"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$FULL_ECR_URI"

      - echo "=== 2. Criação dos Scripts de Execução e Deploy ==="
      
      # -----------------------------------------------------
      # A) CRIAÇÃO: run-prowler.sh (Script de Entrada do Container)
      # -----------------------------------------------------
      - cat <<EOF > run-prowler.sh
#!/bin/bash
set -euo pipefail

# CORREÇÃO CRÍTICA: Força o PATH para que o 'prowler' seja encontrado no Entrypoint
export PATH="/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin"

# === DIAGNÓSTICO INICIAL ===
if ! command -v prowler &> /dev/null; then
    echo "❌ Erro Crítico: 'prowler' não encontrado no PATH! A imagem Docker falhou."
    exit 1
fi

echo "✅ Prowler pronto para uso: \$(command -v prowler)"
prowler --version || echo "⚠️ Não foi possível exibir a versão do prowler."

echo "🛰️ === Iniciando execução do Prowler Runner ==="
echo "📂 Diretório atual: \$(pwd)"
echo "👤 Usuário atual: \$(whoami)"
echo "🔧 PATH atual: \$PATH"

# === VARIÁVEIS OBRIGATÓRIAS ===
: "\${CLOUD_PROVIDER:?❌ CLOUD_PROVIDER não definido (aws | azure | gcp)}"
: "\${TARGET_ACCOUNTS:?❌ TARGET_ACCOUNTS não definido (IDs separados por vírgula ou ALL)}"

REGION="\${AWS_REGION:-us-east-1}"
BUCKET="my-prowler-results"
TIMESTAMP=\$(date +%Y%m%d%H%M)
OUTPUT_DIR="/tmp"
OUTPUTS=()

CLOUD_PROVIDER=\$(echo "\$CLOUD_PROVIDER" | tr '[:upper:]' '[:lower:]')

upload_to_s3() {
    local file="\$1"
    local account="\$2"
    local dest="s3://\${BUCKET}/\${CLOUD_PROVIDER}/\${account}/\${TIMESTAMP}/\$(basename "\$file")"
    echo "📤 Enviando \$file → \$dest"
    aws s3 cp "\$file" "\$dest" --acl bucket-owner-full-control || {
        echo "❌ Falha no upload de \$file"
        return 1
    }
}

run_prowler_generic() {
    local provider="\$1"
    local id="\$2"
    shift 2
    local extra_args=(\"\$@\")

    echo "🚀 Executando Prowler para \${provider^^} → \$id"
    local OUT_FILE="\${OUTPUT_DIR}/prowler-output-\${id}-\${TIMESTAMP}.json"

    # Chamada direta e limpa para 'prowler'
    prowler "\$provider" "\${extra_args[@]}" \
        --output-formats json-asff \
        --output-filename "\$(basename "\$OUT_FILE" .json)" \
        --output-directory "\$OUTPUT_DIR" \
        --ignore-exit-code-3

    if [[ -f "\$OUT_FILE" ]]; then
        echo "✅ Arquivo gerado: \$OUT_FILE"
        OUTPUTS+=("\$OUT_FILE")
        upload_to_s3 "\$OUT_FILE" "\$id"
    else
        echo "❌ Arquivo não encontrado para \$id"
    }
}

# === AWS ===
if [[ "\$CLOUD_PROVIDER" == "aws" ]]; then
    echo "☁️  Selecionado AWS"
    if [[ "\$TARGET_ACCOUNTS" == "ALL" ]]; then
        echo "🔎 Buscando contas AWS no SSM..."
        TARGET_ACCOUNTS=\$(aws ssm get-parameter \
            --name "/prowler/aws/accounts" \
            --query "Parameter.Value" \
            --output text)
    fi

    for ACCOUNT_ID in \$(echo "\$TARGET_ACCOUNTS" | tr ',' ' '); do
        echo "🎯 Conta alvo: \$ACCOUNT_ID"
        CREDS=\$(aws sts assume-role \
            --role-arn arn:aws:iam::\${ACCOUNT_ID}:role/ProwlerAuditRole \
            --role-session-name prowler-session)
        export AWS_ACCESS_KEY_ID=\$(echo "\$CREDS" | jq -r .Credentials.AccessKeyId)
        export AWS_SECRET_ACCESS_KEY=\$(echo "\$CREDS" | jq -r .Credentials.SecretAccessKey)
        export AWS_SESSION_TOKEN=\$(echo "\$CREDS" | jq -r .Credentials.SessionToken)

        run_prowler_generic aws "\$ACCOUNT_ID" --region "\$REGION"

        unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
    done
fi

# === AZURE ===
if [[ "\$CLOUD_PROVIDER" == "azure" ]]; then
    echo "☁️  Selecionado Azure"
    if [[ "\$TARGET_ACCOUNTS" == "ALL" ]]; then
        echo "🔎 Buscando subscriptions Azure no SSM..."
        TARGET_ACCOUNTS=\$(aws ssm get-parameter \
            --name "/prowler/azure/subscriptions" \
            --query "Parameter.Value" \
            --output text)
    fi

    for SUB in \$(echo "\$TARGET_ACCOUNTS" | tr ',' ' '); do
        run_prowler_generic azure "\$SUB" --subscription-id "\$SUB"
    done
fi

# === GCP ===
if [[ "\$CLOUD_PROVIDER" == "gcp" ]]; then
    echo "☁️  Selecionado GCP"
    if [[ "\$TARGET_ACCOUNTS" == "ALL" ]]; then
        echo "🔎 Buscando projetos GCP no SSM..."
        TARGET_ACCOUNTS=\$(aws ssm get-parameter \
            --name "/prowler/gcp/projects" \
            --query "Parameter.Value" \
            --output text)
    fi

    echo "🔑 Recuperando credenciais de service account..."
    aws ssm get-parameter \
        --name "/prowler/gcp/michel/serviceAccountKey" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text | base64 -d > /tmp/prowler-sa.json
    export GOOGLE_APPLICATION_CREDENTIALS="/tmp/prowler-sa.json"

    for PROJECT in \$(echo "\$TARGET_ACCOUNTS" | tr ',' ' '); do
        run_prowler_generic gcp "\$PROJECT" --project-id "\$PROJECT"
    \done
fi

echo "🧾 === Execução finalizada. Relatórios gerados: ==="
printf '%%s\n' "\${OUTPUTS[@]}"
EOF

      # -----------------------------------------------------
      # B) CRIAÇÃO: update-task-definition.sh (Script de Deploy)
      # -----------------------------------------------------
      - cat <<EOF > update-task-definition.sh
#!/bin/bash
set -euo pipefail

# Variáveis passadas do CodeBuild ENV
AWS_REGION=\$AWS_REGION
TASK_FAMILY=\$TASK_FAMILY
CONTAINER_NAME=\$CONTAINER_NAME
NEW_IMAGE_URI=\$NEW_IMAGE_URI

TASK_DEF_FILE="task-definition-new.json"
TASK_DEF_UPDATED_FILE="task-definition-updated.json"

echo "=== 1. Validando e Puxando Task Definition ==="
LATEST_TASK_ARN=\$(aws ecs list-task-definitions \
    --family-prefix "\$TASK_FAMILY" \
    --status ACTIVE \
    --sort DESC \
    --max-items 1 \
    --query 'taskDefinitionArns[0]' \
    --output text)

if [ "\$LATEST_TASK_ARN" = "None" ] || [ -z "\$LATEST_TASK_ARN" ]; then
    echo "❌ ERRO: Família de Tarefa '\$TASK_FAMILY' não encontrada. Abortando atualização."
    exit 1
fi

echo "✅ ARN ativo: \$LATEST_TASK_ARN. Puxando JSON..."

aws ecs describe-task-definition \
    --task-definition "\$LATEST_TASK_ARN" \
    --query 'taskDefinition' \
    | jq 'del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities)' \
    > "\$TASK_DEF_FILE"

echo "=== 2. Atualizando URI da Imagem (\$CONTAINER_NAME) ==="

jq --arg img "\$NEW_IMAGE_URI" \
   --arg name "\$CONTAINER_NAME" \
   '(.containerDefinitions[] | select(.name == \$name).image) = \$img' \
   "\$TASK_DEF_FILE" > "\$TASK_DEF_UPDATED_FILE"

UPDATED_COUNT=\$(cat "\$TASK_DEF_UPDATED_FILE" | jq "(.containerDefinitions[] | select(.name == \"\$CONTAINER_NAME\") | .image) | select(.)" | wc -l)

if [ "\$UPDATED_COUNT" -eq 0 ]; then
    echo "❌ ERRO: Não foi possível atualizar o contêiner '\$CONTAINER_NAME'. Nome incorreto?"
    exit 1
fi

echo "✅ URI da imagem atualizada para \$NEW_IMAGE_URI."

echo "=== 3. Registrando Nova Revisão ==="

NEW_REVISION_ARN=\$(aws ecs register-task-definition \
    --cli-input-json file://"\$TASK_DEF_UPDATED_FILE" \
    --query 'taskDefinition.taskDefinitionArn' \
    --output text)

echo "====================================================="
echo "           ✅ SUCESSO! NOVA REVISÃO CRIADA"
echo "Nova Revisão ARN: \$NEW_REVISION_ARN"
echo "====================================================="

rm "\$TASK_DEF_FILE" "\$TASK_DEF_UPDATED_FILE"
EOF

      # === 3. FINALIZAÇÃO DA CRIAÇÃO DE SCRIPTS ===
      - chmod +x run-prowler.sh update-task-definition.sh

  build:
    commands:
      # Build: Focado em construir e taguear
      - echo "=== Construindo imagem Docker ==="
      - docker build -t prowler-repo-local -f Dockerfile.prowler .
      - docker tag prowler-repo-local:latest "$NEW_IMAGE_URI"

  post_build:
    commands:
      # Deploy: Focado em push e atualização da Task Definition
      - echo "=== 1. Publicando imagem no ECR ==="
      - docker push "$NEW_IMAGE_URI"

      - echo "=== 2. Executando Atualização da Definição de Tarefa ECS ==="
      - export NEW_IMAGE_URI="$NEW_IMAGE_URI" # Garante que a variável seja passada
      - ./update-task-definition.sh

      - echo "=== Build e Deploy Concluídos com Sucesso ==="

artifacts:
  files: []
