version: 0.2

env:
  variables:
    ECR_REPO: "057959860487.dkr.ecr.us-east-1.amazonaws.com/multicloud-prowler-repo"

phases:
  install:
    commands:
      - echo "=== Fase INSTALL ==="
      - yum update -y
      - yum install -y unzip tar gzip curl jq awscli docker

  pre_build:
    commands:
      - echo "=== Login no ECR ==="
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo "Login no ECR concluído"

  build:
    commands:
      - echo "=== Construindo imagem Docker ==="
      - docker build -t prowler-repo -f Dockerfile.prowler .
      - docker tag prowler-repo:latest "$ECR_REPO:latest"

  post_build:
    commands:
      - echo "=== Publicando imagem no ECR ==="
      - docker push "$ECR_REPO:latest"
      - echo "=== Build concluído com sucesso ==="

artifacts:
  files: []
