---
version: 0.2

env:
  variables:
    ECR_REPO: "057959860487.dkr.ecr.us-east-1.amazonaws.com/multicloud-prowler-repo"

phases:
  install:
    commands:
      - echo "=== Instalando dependências no ambiente de build ==="
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "=== Login no ECR ==="
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$ECR_REPO"

  build:
    runtime-versions:
      docker: 20
    privileged: true
    commands:
      - echo "=== Construindo imagem Docker (forçando rebuild limpo) ==="
      - docker build --no-cache -t prowler-repo -f Dockerfile.prowler .
      - docker tag prowler-repo:latest "$ECR_REPO:latest"
      - echo "=== Validando binário prowler dentro da imagem ==="
      - docker run --rm prowler-repo which prowler || (echo "❌ Prowler não encontrado!" && exit 1)
      - docker run --rm prowler-repo whoami

  post_build:
    commands:
      - echo "=== Publicando imagem no ECR ==="
      - docker push "$ECR_REPO:latest"
      - echo "=== Build concluído com sucesso ==="

artifacts:
  files: []
