version: 0.2

env:
  variables:
    ECR_REPO: "057959860487.dkr.ecr.us-east-1.amazonaws.com/multicloud-prowler-repo"
    IMAGE_TAG: "latest"
    AWS_REGION: "us-east-1"

phases:
  install:
    commands:
      - echo "=== 🧩 Validando ambiente CodeBuild ==="
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "=== 🔐 Login no ECR ==="
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$ECR_REPO"

  build:
    commands:
      - echo "=== 🏗️ Construindo imagem Docker (MultiCloud Prowler Runner) ==="
      - docker build -t prowler-runner .
      - docker tag prowler-runner:latest "$ECR_REPO:$IMAGE_TAG"

  post_build:
    commands:
      - echo "=== 🚀 Publicando imagem no ECR ==="
      - docker push "$ECR_REPO:$IMAGE_TAG"
      - echo "✅ Build concluído com sucesso: $ECR_REPO:$IMAGE_TAG"

artifacts:
  files: []
