---
version: 0.2

env:
  variables:
    ECR_REPO: "057959860487.dkr.ecr.us-east-1.amazonaws.com/multicloud-prowler-repo"

phases:
  install:
    commands:
      - echo "=== Validando dependências ==="
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "=== Login no ECR ==="
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "057959860487.dkr.ecr.us-east-1.amazonaws.com"

  build:
    commands:
      - echo "=== Construindo imagem Docker sem git clone ==="
      - docker build -t prowler-repo -f Dockerfile.prowler .
      - docker tag prowler-repo:latest "$ECR_REPO:latest"

  post_build:
    commands:
      - echo "=== Publicando imagem no ECR ==="
      - docker push "$ECR_REPO:latest"
      - echo "=== Build concluído com sucesso ==="

artifacts:
  files: []
