# Usa a imagem pública do Prowler no ECR público da AWS
FROM public.ecr.aws/prowler-cloud/prowler:latest

# Instala ferramentas extras necessárias (se o script run-prowler.sh exigir)
RUN yum install -y jq awscli git && yum clean all

# Copia seu script pro container
COPY run-prowler.sh /usr/local/bin/run-prowler.sh
RUN chmod +x /usr/local/bin/run-prowler.sh

# Define entrypoint
ENTRYPOINT ["/usr/local/bin/run-prowler.sh"]
